name: DOCKER CI/CD

on:
  push:
    branches: [ develop ]
env:
  DOCKER_IMAGE: ghcr.io/wendyunji/ci-cd
  VERSION: ${{ github.sha }}
  NAME: test_container

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v2
      - name: Set up docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ env.VERSION }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Login to ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.OWNHUB }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:${{ env.VERSION }}

  deploy:
    needs: build
    name: Deploy
    runs-on: [ self-hosted, label-go ]
    steps:
      - name: Login to ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.OWNHUB }}
      - name: Docker run
        run: |
          docker stop ${{ env.name }} && docker rm ${{ env.NAME }} && docker rmi ${{ env.DOCKER_IMAGE }}:${{ env.VERSION }}
          docker run -d -p 80:80 --name cicd --restart always ${{ env.DOCKER_IMAGE }}:${{ env.VERSION }}
          
  cleanup:
    needs: [ build, deploy ]
    name: Clean up docker images
    runs-on: [ self-hosted, development ]
    steps:
      -   name: Clean up docker images
          run:
            docker rmi $(docker images --filter "before=${{ env.DOCKER_IMAGE }}:${{ env.VERSION }}" --filter=reference="${{ env.DOCKER_IMAGE }}:*" -q)
